// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PublicParkAPI.Data;

namespace PublicParkAPI.Migrations
{
    [DbContext(typeof(PublicParkAPIContext))]
    partial class PublicParkAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("PublicParkAPI.Models.Lugar", b =>
                {
                    b.Property<int>("LugarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Andar")
                        .HasColumnType("int");

                    b.Property<string>("Fila")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Freguesia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<double>("Preco")
                        .HasColumnType("float");

                    b.Property<string>("Rua")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LugarId");

                    b.ToTable("Lugar");
                });

            modelBuilder.Entity("PublicParkAPI.Models.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Duracao")
                        .HasColumnType("int");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LugarId")
                        .HasColumnType("int");

                    b.Property<int?>("Nif")
                        .HasColumnType("int");

                    b.HasKey("ReservaId");

                    b.HasIndex("LugarId");

                    b.HasIndex("Nif");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("PublicParkAPI.Models.User", b =>
                {
                    b.Property<int>("Nif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nif");

                    b.ToTable("User");
                });

            modelBuilder.Entity("PublicParkAPI.Models.Reserva", b =>
                {
                    b.HasOne("PublicParkAPI.Models.Lugar", "Lugar")
                        .WithMany()
                        .HasForeignKey("LugarId");

                    b.HasOne("PublicParkAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Nif");

                    b.Navigation("Lugar");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
