// <auto-generated />
using System;
using Api_DebitoDireto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api_DebitoDireto.Migrations
{
    [DbContext(typeof(Api_DebitoDiretoContext))]
    partial class Api_DebitoDiretoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Api_DebitoDireto.Models.DebitoDireto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("codigoPostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("custo")
                        .HasColumnType("float");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<string>("freguesia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iban")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nifDestinatario")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rua")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("DebitoDireto");
                });
#pragma warning restore 612, 618
        }
    }
}
